### PR TITLE
sample program

### PR DESCRIPTION
**Pull request by KbRama**

### CODE REVIEW

**Comment by yangli-io** [comment]
Don't merge it, let me review it first

**Comment by yangli-io** [comment]
Welldone, it looks like it's working.  You still need to do an `npm init` to create a package.json and when you install packages do a `npm install connect --save` so it saves it to the package.json

**Comment by KbRama** [comment]
Wanted information on this one : npm install connect serve-static ??

**Comment by yangli-io** [comment]
Yeah you can do that just add the `--save`

**Pull request merged**
